services:
  - type: web
    name: rolpay
    runtime: node
    plan: free
    buildCommand: rm -rf node_modules && npm install --include=dev && npm run build
    startCommand: npm start
    envVars:
      - key: JWT_SECRET
        generateValue: true
